# Generated by Django 2.2.9 on 2020-01-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='icon',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
